# -*- coding: utf-8 -*-
"""First.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/157lTz9CZc4-gtuDO_zalpwd9L-KC8gjx
"""

def hello():
  print ("hello world")
def world():
  print ("hello world")