# -*- coding: utf-8 -*-
"""second.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nUd5rGKSshrUusEF_fValNm96YbiCI8C
"""

def hello ():
  print ("hellow virtual world")
def world ():
  print ("hello real world")

