# -*- coding: utf-8 -*-
"""third.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1avUX9ts1ALLJ9c4eK_wbQWJMOBOKioP-
"""

def third():
  print("this is exciting opportunity")